site_name: IJLRA Cheat Sheets

nav:
    - Home: index.md
    - IJLRA: ijlra.md
    - IJLRA / Admin: ijlra-extra-admin.md
    - IJLRA / LAM: lam.md
    - IJLRA / LAM / Espaces Sonores: lam-es.md

theme:
    # name: readthedocs
    # name: mkdocs
    name: material
    logo: img/logo.jpg
    favicon: img/favicon.png

    # material specific options
    palette:
        # scheme: perso
        # accent: amber
        # primary: yellow
        primary: white
        accent: light blue


    font:
        text: Roboto
        code: Roboto Mono

    # features:
    #     - header.autohide

copyright: David Poirier-Q.

# extra_css:
#     - stylesheets/extra.css

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://pyrapple.github.io/
          # name: personal website
    # copyright: 2022 David Poirier-Q.
    # generator: false # remove mention "made with material for mkdocs"