site_name: IJLRA Cheat Sheets

nav:
    - Home: index.md
    - IJLRA: ijlra.md
    - IJLRA / LAM: lam.md
    - IJLRA / LAM / Espaces Sonores: lam-es.md

theme:
    # name: readthedocs
    # name: mkdocs
    name: material
    logo: img/logo.jpg
    favicon: img/favicon.png

    # material specific options
    palette:
        # primary: blue grey
        primary: white

    font:
        text: Roboto
        code: Roboto Mono

    # features:
    #     - header.autohide

    copyright: Copyright &copy; 2016 - 2020 Martin Donath

    # extra:
    #     social:
    #         - icon: fontawesome/brands/twitter
    #           link: https://twitter.com/squidfunk
    #           name: squidfunk on Twitter
    #     # copyright: 2022 David Poirier-Q.
    #     generator: false # remove mention "made with material for mkdocs"
